# Generated by Django 3.2 on 2023-04-15 20:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='text',
            field=tinymce.models.HTMLField(help_text='введите ваше описание курса', verbose_name='описание'),
        ),
    ]
